CREATE TABLE TG_USERS(
ID INTEGER  PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255),
USERNAME VARCHAR(255),
EMAIL VARCHAR(255),
CONTACT VARCHAR(255),
ADDRESS VARCHAR(255),
PIC VARCHAR(100),
IS_ADMIN BIT(1),
STATUS BIT(1)
);