CREATE TABLE TG_ORGANIZATION(
ID INTEGER  PRIMARY KEY AUTO_INCREMENT,
ORG_NAME VARCHAR(255) NOT NULL,
ORG_LOGO VARCHAR(255),
ORG_ADDRESS VARCHAR(255),
ORG_PARENT INTEGER,
ORG_EMAIL VARCHAR(120),
ORG_CONTACT VARCHAR(255),
ORG_STATUS BIT(1),
);